### ISSUE TITLE
Instance not listed

### ISSUE THREAD

**Issue by jimboolio** [TheKinrar/mastodon-instances#100]
Hello!

For some reason my instance isn't listed on instances.social. My instance is called jako.social and I verified my ownership and submitted the descriptions on 27th  or 28th of January. I did not see any error messages (except missing favicon) or anything to comment why it isn't listed. If there's something I could check or fix on my side I would be happy to do that to get my instance listed

**Comment by singlespeedfahrer** [comment]
Same here for instance subversive.zone about two weeks ago.

**Comment by downeymj** [comment]
From checking the instance log under https://instances.social/jako.social and https://instances.social/subversive.zone it would seem that both of these seem to be the same issue as #77 which is still unresolved.

**Comment by TheKinrar** [comment]
From what I can see both instances are up-to-date on their pages and show up in the list.
![image](https://user-images.githubusercontent.com/8020878/129992286-825f13d5-1dbf-4cb6-ab8c-818460d1abad.png)

**Comment by TheKinrar** [comment]
Closing for now, reopen if I missed something
