### ISSUE TITLE
Does the database contain all Mastodon instance data? Cannot find mastodon.technology

### ISSUE THREAD

**Issue by ayush-sharma** [TheKinrar/mastodon-instances#102]
I cannot find the [mastodon.technology](https://mastodon.technology/) instance in the API results. See screenshot:

<img width="1434" alt="Screenshot 2021-09-21 at 2 51 39 PM" src="https://user-images.githubusercontent.com/9398523/134146151-76043306-e6c0-4ee7-9fd5-ec316b63f505.png">

Sorry if this has been asked and answered somewhere else, but:

1. Does the API/DB contain all Mastodon instances currently deployed?
2. Is it up to the instance admins to add their instance to the API, or is the data auto-discovered somehow?
3. Are fake instances also added to the DB? The API is currently also returning [this fake instance](https://you-think-your-fake-numbers-are-impressive.well-this-instance-contains-all-living-humans.lubar.me/).

**Comment by TheKinrar** [comment]
1. It tries to contain as much as possible, I would say!
2. No it's auto-discovered through the /instance/peers endpoint where instances list all the other instances they know
3. Sadly yes, and we have to rely on manual actions to remove them. Something could be done to automatically remove obviously fake numbers I think
