### ISSUE TITLE
Broken content in `openRegistrations` field in JSON for a single instance

### ISSUE THREAD

**Issue by EliotBerriot** [TheKinrar/mastodon-instances#11]
In the JSON available at https://instances.mastodon.xyz/instances.json, you can find the following:

```
{
   "name":"design.vu",
   "uptime":35.92528236316247,
   "up":false,
   "https_score":90,
   "https_rank":"A",
   "ipv6":false,
   "openRegistrations":{
        "code":"ENOTFOUND",
        "errno":"ENOTFOUND",
        "syscall":"getaddrinfo",
        "hostname":"design.vu",
        "host":"design.vu",
        "port":443
    },
   "users":23,
   "statuses":83,
   "connections":105
}
```
As you can see, the `openRegistrations` key is not a boolean, but an object containing an error. I think there is maybe some error occuring that is returned and embedded in your data, instead of being treated as an error.

This is not a real big deal, since at the moment, it's only occuring on a single instance, but it makes the number of instances [my dashboards](https://mnm.eliotberriot.com) slightly behind yours ;)

**Comment by TheKinrar** [comment]
Fixed in 0f3d540f9321add4ff17ecc558bb90db320a76cf.

Thanks!
