### ISSUE TITLE
Défilement automatique

### ISSUE THREAD

**Issue by vincentux** [TheKinrar/mastodon-instances#12]
Bonjour,
est-il possible d'avoir le choix dans le mode de défilement des "pouets"  via une option dans les paramètres peut-être ? _Je parle pas du défilement auto des fils local ou global mais juste celui de mes abonnement._

Genre pouvoir choisir entre défilement auto ou choisir un mode qui cumulerait les "pouets" non lus, et afficherait "afficher les n pouets non lus" (par exemple), comme sur Twitter.

![twitter](https://cloud.githubusercontent.com/assets/11737560/24952231/290fdfd6-1f77-11e7-87b5-1f06ee354be3.PNG)

ps : ils en parlent ici je crois : [#1538](https://github.com/tootsuite/mastodon/issues/1538)

**Comment by TheKinrar** [comment]
Oui absolument c'est de ça dont il est sujet là-bas.

Par contre ici c'est le repo de la liste d'instances donc cette issue n'a pas de place ici (d'autant que déjà existante sur le repo de mastodon comme tu l'as fait remarqué).

**Comment by vincentux** [comment]
> Par contre ici c'est le repo de la liste d'instances

Oups désolé ...
