### ISSUE TITLE
Problem on HTTPS_score JSON file

### ISSUE THREAD

**Issue by Sp3r4z** [TheKinrar/mastodon-instances#15]
Correct the https score on some instances, it's like "F, A+, F, F". It seems to be a problem with float numbers. But: observatory and Imirhil don't seem to answer with a floating value

**Comment by TheKinrar** [comment]
This is probably a normal behavior. Can you give the name of an instance in this case ?

**Comment by Sp3r4z** [comment]
social.dropbear.xyz
s.dat.cloud
zaksoup.club
k0ta.net
teitoku.to
spod.ca
mstdn.wolflab.net
toot.memtech.website
mastodon.business

Maybe a problem with Imirhil https scoring?

**Comment by TheKinrar** [comment]
So this isn't actually a bug nor a problem.

social.dropbear.xyz has score A+, F, F, F because it has different scores on different IP addresses. See https://tls.imirhil.fr/https/social.dropbear.xyz
