### ISSUE TITLE
No instance updates since Oct 5

### ISSUE THREAD

**Issue by mszell** [TheKinrar/mastodon-instances#166]
Hi, same issue as last time: https://github.com/TheKinrar/instances/issues/144

**Comment by TheKinrar** [comment]
What makes you believe that? I checked numbers for xyz and social and they match

**Comment by mszell** [comment]
Oops I am sorry I should have double-checked.
It is actually the same tool by @mauforonda that didn't update since Oct 5, and I just assumed it to be the same issue as last time: https://observablehq.com/@mauforonda/what-goes-on-in-mastodon
