### ISSUE TITLE
Block bad instances

### ISSUE THREAD

**Issue by ticki** [TheKinrar/mastodon-instances#18]
For example, this: https://github.com/ticki/mastodon-blacklist

**Comment by TheKinrar** [comment]
I won't censor the list. Period.

This is censorship. So that's a no.
In the new release coming this evening, it will be publicly visible wether instances moderate racism, sexism, etc.
People choose the instances they want and I don't want to influence their choice.

**Comment by ticki** [comment]
> This is censorship. So that's a no.

its not but whatever
