### ISSUE TITLE
Wizard doesn't filter results if selected requirements *do* matter

### ISSUE THREAD

**Issue by albocc** [TheKinrar/mastodon-instances#21]
The wizard offers the user the choice to select certain requirements on what content is allowed on the instances it returns as a result. For each requirement you can select "Authorized", "No matter" and "Denied". By default all the requirements are set to "No matter" which should not restrict the results of the wizard. 

However, if you select "Authorized" for all requirements you don't get the expected result of only those instances getting listed that allow for all requirements, but [instead you get a sorted list](https://mastodon.xyz/@TheKinrar/4382401) that matches the desired choice of requirements the best. Since "Authorized" and "Denied" are by definition of the web form alternatives to "Doesn't matter", the choice of picking the former two **does** matter and the wizard shouldn't return results that don't match all the criteria. In other words, the current behavior of sorting should be changed to filtering where "No matter" is a wild card that basically skips the requirement while filtering. 

Alternatively – or better, as a short-term workaround – the wizard can keep its current behavior of doing simple sorting, but highlight those results that don't match all the requirements.

**Comment by TheKinrar** [comment]
New version of the list includes an "advanced mode" which will only show perfect matches.

Releasing this week.
