### ISSUE TITLE
Add a way of changing the current search

### ISSUE THREAD

**Issue by albocc** [TheKinrar/mastodon-instances#23]
Currently, the wizard doesn't offer a way to change the search the user just performed. Instead, the user has to go through all the questions (in the default setting) again, if he decides he wants to change one of his previous answers. 

To fix this, there should be a quick and easy way of going back to a specific question from the results page. As a short-term solution the wizard could pre-fill the answers of the questionnaire, if the user clicks on the "Open Wizard" button on the results page. This way the user still has to go through all the questions, but he can rather quickly skip the questions he doesn't want to change.

**Comment by TheKinrar** [comment]
Done in the new version of the list, coming this week.
