### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by Wonderfall** [TheKinrar/mastodon-instances#25]
When you click on an instance from the list, the correct description should be displayed. If you click on another without refreshing the page, the description from the previous instance will be displayed.

**Comment by TheKinrar** [comment]
Is this systematic for you? I can't reproduce the bug, can you look into the development console of your navigator while using the list?

**Comment by Wonderfall** [comment]
This is systematic. What do you want me to do exactly?

I only got this error but this happens and the page is loading : 

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

If this can help, I use Chromium (through Vivaldi).

**Comment by TheKinrar** [comment]
Okay, so, nothing unexpected. Just tested with Chromium and it works too.

Can you try with another browser please?

**Comment by Wonderfall** [comment]
Same problem with Firefox 54.
