### ISSUE TITLE
Language search not working normally

### ISSUE THREAD

**Issue by Slaynash** [TheKinrar/mastodon-instances#26]
If I set language to French, less than 100 users and "no matters" on all restrictions, I got some non-french instances on the list
![image](https://user-images.githubusercontent.com/5593503/27256196-64b106da-53ae-11e7-8738-0575e96d10cf.png)
![image](https://user-images.githubusercontent.com/5593503/27256199-6c4074ee-53ae-11e7-9655-7e381e94a371.png)

**Comment by TheKinrar** [comment]
That's because, currently, the wizard only sorts instances but doesn't filter them.
Some improvements are coming for this.

But, at this time, this is a normal behavior. Instances that match best your criteria are on the top.
