### ISSUE TITLE
Moderation filters don't work

### ISSUE THREAD

**Issue by smonff** [TheKinrar/mastodon-instances#28]
When combining many moderation filters, it returns wrong results.

For example, I tried with instances that allows sexism + racism + hate speech + harassment and it returns instances that have a clear CoC against those.

I am doing something wrong? 

![screen shot 2017-07-02 at 16 56 26-fullpage](https://user-images.githubusercontent.com/1219097/27771303-7796dc4e-5f4c-11e7-805c-110d6c4e2c20.png)

**Comment by TheKinrar** [comment]
Same response as #26: this is a normal behavior currently as the wizard sorts the instances by accuracy instead of filtering them.

Next version (already developed, coming soon) will have advanced parameters and real filters.
