### ISSUE TITLE
Make site translatable

### ISSUE THREAD

**Issue by mkljczk** [TheKinrar/mastodon-instances#31]
Great work, great list of instances. Will there be ability to translate this page and select translation on instances.social? I would make Polish translation.
- [ ] i18n support
- [ ] my Polish translation

**Comment by m4sk1n** [comment]
@TheKinrar, can you assign me and add `work in progress` label?

**Comment by m4sk1n** [comment]
oh no, I probably won't finish it too fast… I'll probably give up

**Comment by TheKinrar** [comment]
> oh no, I probably won't finish it too fast… I'll probably give up

no big deal, tell me if you stop :)

**Comment by jelv** [comment]
For SEO purpose it would be good to give each language dedicated url. Something like instances.social/nl and instances.social/fr
