### ISSUE TITLE
Generating large percentage of load on Mozilla HTTP Observatory

### ISSUE THREAD

**Issue by april** [TheKinrar/mastodon-instances#33]
Hey there! I'm the primary developer and sysadmin of the Mozilla Observatory. It's great that instances.social is using the Observatory to score sites, but it's generating a significant percentage of our load, sometimes well over half.

Would it be possible to ask you to cache the results for 24 hours, instead of querying the Observatory as frequently? The Observatory is already doing so, but it's adding significant stress on our infrastructure. At Mozilla we have a lot of our own sites that we scan, but by caching the JSON results it really helps keep our server costs down.

Thanks so much, please let me know if you have any questions!

**Comment by TheKinrar** [comment]
Hi :)

That's something I've been planning to do for a long time but I didn't think it was so impacting your servers.
Fixing this right now.

**Comment by april** [comment]
Thank you, I really appreciate it.  I've since bumped up our number of instances to handle the load, but it would be nice to not have to worry about it.  Thank you!  :)

**Comment by TheKinrar** [comment]
Fix has been pushed, you should get less and less requests in the next minutes.
