### ISSUE TITLE
502 on POST to /admin/sign_up

### ISSUE THREAD

**Issue by voteblake** [TheKinrar/mastodon-instances#37]
I'm receiving a 502 when attempting to sign up a new instance. Confirmed over IPv4 and IPv6.

Form data on POST is:

instance: sdr.haus

**Comment by TheKinrar** [comment]
I can't see any instance at https://sdr.haus so it's quite normal it doesn't work.

Anyway, I removed the invalid label because a 502 should not be returned.

**Comment by voteblake** [comment]
Ah, sorry for that, started again giving the WEB_DOMAIN of the instance rather than the LOCAL_DOMAIN and everything worked.
