### ISSUE TITLE
Advanced search returns empty table

### ISSUE THREAD

**Issue by turion** [TheKinrar/mastodon-instances#39]
This page gives an empty table on my browser: https://instances.social/list/advanced#lang=en,de,es&allowed=&prohibited=illegalContentLinks,spam,advertising&users=100000
But clearly there are a lot of instances satisfying the filters.

**Comment by TheKinrar** [comment]
Normal behavior. Advanced mode performs a strict match. There's no instance having English, German and Spanish as main languages and prohibiting illegal content links, spam and advertising.

**Comment by TheKinrar** [comment]
Maybe you'll find something with less strict languages filters.
