### ISSUE TITLE
What is the significance of "grades"/score in columns

### ISSUE THREAD

**Issue by chigh** [TheKinrar/mastodon-instances#42]
What is the significance of the "grades"/score in the **HTTPS** and **Obs** columns? And for that matter, what does the **Obs** column mean?

**Comment by TheKinrar** [comment]
HTTPS score comes from https://tls.imirhil.fr
Obs is Observatory by Mozilla: https://observatory.mozilla.org

**Comment by chigh** [comment]
Thanks!
