### ISSUE TITLE
Sign Up button does nothing

### ISSUE THREAD

**Issue by joshuatj** [TheKinrar/mastodon-instances#44]
Hi, I was planning to add an instance to the list. Found the admin space but it would seem that the sign up button does nothing when clicked.

**Comment by TheKinrar** [comment]
Looks like I'm a bit late. Still relevant? Which instance?

**Comment by Kansattica** [comment]
I find that when I go to the admin panel, type my instance name (social.illegalpornography.com) into the sign-up box, and hit enter in Chrome, the text box just clears. If I click the button, it tells me:

> Something went wrong. Check the instance name is valid and a contact email is set in the site settings of Mastodon. Contact @TheKinrar@mastodon.xyz if you need help.

I don't know if this is the same as what joshuatj is dealing with, but it sounds similar.

**Comment by TheKinrar** [comment]
I'm currently finish a full rewrite of the registration process. This should be released during the evening.

**Comment by steckerhalter** [comment]
ok, thanks

**Comment by TheKinrar** [comment]
New admin space has been pushed (commit 43d435d733e02ea3d0baacd60e03b89f960db538).

https://instances.social/admin

**Comment by steckerhalter** [comment]
@TheKinrar with the new process the email is now sent and I could sign up my instance, thanks :clap:
