### ISSUE TITLE
PW reset

### ISSUE THREAD

**Issue by Openmedianetwork** [TheKinrar/mastodon-instances#45]
I have two instances and cant login for to the instance site, think its wrong PW issue - but cant find PW reset. Can you help as need to add category to them. 

https://campaign.openworlds.info
https://activism.openworlds.info

Hamish

**Comment by TheKinrar** [comment]
Deleted the admin accounts for these instances so that you can register again with a new password.

**Comment by Openmedianetwork** [comment]
Hummm but these are active accounts being used, so the is a cost to close them. can the not be a PW reset option?

**Comment by TheKinrar** [comment]
How can they be used if you didn't have the password? Deleting accounts does not delete instance data.

I'll add a reset PW feature, but later.

**Comment by Openmedianetwork** [comment]
Ahaa.. I misread your English you removed the accounts at your end :)

OK fixed and uploaded agen, thanks for the help.
