### ISSUE TITLE
Thumbnails/previews not working - HTTPS error

### ISSUE THREAD

**Issue by ineffyble** [TheKinrar/mastodon-instances#49]
I noticed on joinmastodon.org that none of the thumbnails are showing.

I can see the image URL is 

https://camo.instances.social/ba8023c906679e19084e33a76463b817f4af048d/68747470733a2f2f6173736574732e6d7374646e2e6a702f7061636b732f707265766965772d39613137643332666334383336396538636364393130613735323630653637642e6a7067

Which is broken - presenting a certificate for dashboards-diabete.thekinrar.fr

**Comment by ineffyble** [comment]
cc @Gargron

**Comment by TheKinrar** [comment]
Fixed, thanks.
