### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gellenburg** [TheKinrar/mastodon-instances#50]
Receiving an "Internal Server Error" when attempting to login to the Admin Space.

**Comment by TheKinrar** [comment]
Which instance?

**Comment by Turbito** [comment]
Same here. Attempting to access into admin space I get the error message Internal Server Error

I own piscolabis.me

Also, instances  dot social says the register is closed in my instance when It is not

**Comment by TheKinrar** [comment]
New admin space has been pushed (commit 43d435d733e02ea3d0baacd60e03b89f960db538).

https://instances.social/admin

If your issue persists, please contact me at contact@thekinrar.fr. Thanks.
