### ISSUE TITLE
Filtering in simple mode seems to ignore filters

### ISSUE THREAD

**Issue by renatolond** [TheKinrar/mastodon-instances#58]
Hey!

Masto.donte has some prohibited content:
![image](https://user-images.githubusercontent.com/173791/39353771-f993165c-4a08-11e8-9e2a-82f457c7e9b4.png)

However, when in simple mode, we can still see it appearing in the instances list with this selection:
![image](https://user-images.githubusercontent.com/173791/39353791-0d619c4e-4a09-11e8-954a-2f6e09627f66.png)

If I change to advanced mode, it's not the case anymore:
![image](https://user-images.githubusercontent.com/173791/39353818-1df8ea08-4a09-11e8-9911-7936e1beefba.png)

I think there's some issue with the filtering in the simple mode

**Comment by TheKinrar** [comment]
Simple mode uses some kind of best-match sort, it tries to find instances that match most of the filters and sorts them according to how close the match is. It should probably be made more explicit on the website though.
