### ISSUE TITLE
Results inaccurate

### ISSUE THREAD

**Issue by lawremipsum** [TheKinrar/mastodon-instances#60]
The results displayed for mspsocial.net are wrong and it's not apparent what I as an instance administrator need to do to fix them.

![image](https://user-images.githubusercontent.com/33725621/43431527-d70e7bf6-9433-11e8-880c-d21160551ca6.png)
![image](https://user-images.githubusercontent.com/33725621/43431541-ecc704c2-9433-11e8-8f4f-79588129ebbb.png)
![image](https://user-images.githubusercontent.com/33725621/43431578-1195cd06-9434-11e8-9097-dfa510d2fbfe.png)

79% uptime implies that the site is down for 4 hours every day. It is not. I don't know what's causing the connection errors but my users would complain if I approached that level of unreliability. It's not accurate.

I'm concerned that the inaccuracy will give people a mistaken impression of the reliability or security of the instance.

**Comment by TheKinrar** [comment]
This was a bug on my servers, fixed since. Uptimes have been reset.

**Comment by pietsch** [comment]
I see a similar inaccuracies and a similar instance log here: https://instances.social/digitalcourage.social

User count, status count, connections, uptime – all of your numbers are way off.

Is it because digitalcourage.social is reachable via IPv4 only?

**Comment by TheKinrar** [comment]
Worker was down, your stats should be up to date now

**Comment by pietsch** [comment]
> Worker was down, your stats should be up to date now

Thank you! User count is accurate now. The uptime you show is still wrong.

**Comment by TheKinrar** [comment]
Uptime has been wrong for a long time. I do not have the time to actively maintain instances.social nowadays.
I hope I'll be able to work on this one day.

**Comment by MaximilianKohler** [comment]
>Uptime has been wrong for a long time. I do not have the time to actively maintain instances.social nowadays.
I hope I'll be able to work on this one day.

Is that still the case? If so, it would be useful to have some kind of notice on the page. For example, I was curious to see which servers allow "links to illegal content" https://instances.social/list/advanced#lang=&allowed=illegalContentLinks&prohibited=&min-users=&max-users=

It lists mstdn.social, but when I go there it clearly says "no illegal content" https://mstdn.social/auth/sign_up

It also incorrectly removes them after selecting "english" https://instances.social/list/advanced#lang=en&allowed=&prohibited=&min-users=&max-users=
