### ISSUE TITLE
"Humor" category?

### ISSUE THREAD

**Issue by nolanlawson** [TheKinrar/mastodon-instances#62]
Thanks very much for running instances.social! My wife is the admin of https://freedom.horse, and she'd like to have a "humor" category for sites like freedom.horse, wafflec.one, banana.dog, etc. Does this sound like a reasonable category to add?

(P.S. perfectly fine to say "humour" as well, but I'm a Yankee so that's my preference. 😉)

**Comment by TheKinrar** [comment]
Added!

**Comment by nolanlawson** [comment]
Awesome, thank you! :tada:
