### ISSUE TITLE
i know this is not an issue

### ISSUE THREAD

**Issue by camarigor** [TheKinrar/mastodon-instances#64]
I'm try to get my instance verified but i never receive the confirmation email. i'm trying to contact TheKinrar but he never answer my toots and my messages. Is there another why to fix that? Because is a little bit annoying try to support mastodon and that guy is unreachable.
Thanks in advance

**Comment by TheKinrar** [comment]
Fuck I'm not unreachable, that's definitely wrong. Send an email to contact@thekinrar.fr or DM me on Mastodon and just WAIT. I'm not a robot and sometimes I can't answer as fast as you'd like.
