### ISSUE TITLE
Please reject incorrect instance name.

### ISSUE THREAD

**Issue by mjyut** [TheKinrar/mastodon-instances#69]
Some administrators confuse the "account name" (`username@instance_name`) with the "instance name" (`domain.name`).

* Please refuse it when they register. Also, tell them to enter the correct "instance name".
* Please delete already registered incorrect instances from the database.

List of incorrectly registered instance names:

```
@ndyk.de
fusagiko@imastodon.net
violet@chitter.xyz
@mastodon.yuritopia.net
afterdarkadmin@yiff.fyi
erikxxon@orebrotribune.online
@shikokudon.m.to
@zone53.champemedylan.fr
@sasakitz@mstdn.cc
@nice.community
@nfg.zone
@jasperisnthere@chaos.social
admin@mastoc.net
contact@mastoc.net
@mastodon.baucum.me
@negotiator@vulturion.com
@mastodon.com.pl
@spoofy@mastodon.com.pl
bofh@mastodon.social
admin@mastodon.com.pl
@bongmines@mastodon.xyz
@gadgetvirtuoso@moseisley.club
@social.tedliou.com
@tyrent@mastodon.social
@nosti@mastodon.xtenz.xyz
@mastodon.xtenz.xyz
sysadmin@mastodon.xtenz.xyz
@social.illegalpornography.com
@bestgirlgrace@social.illegalpornography.com
bestgirlgrace@social.illegalpornography.com
kenzo@innerwebs.social
@se7entime@mstdn.id
@yohei_zuho@mstdn.y-zu.org
@mookie@trblmkr.net
echoz@kopiti.am
@kopiti.am
glorificatio@mstdn.glorificatio.org
@mattsocialadmin@matt-social.co.uk
@rf@mastodon.xyz
@parleur@mastodon.parleur.net
```

Thank you for reading. 😄

**Comment by TheKinrar** [comment]
Registering on https://instances.social/admin with such names is already handled correctly and should just ignore the `user@` part. I assume these instances were added before 43d435d733e02ea3d0baacd60e03b89f960db538, and I'll just delete them.

**Comment by mjyut** [comment]
Thank you for deleting the incorrect  instance from the DB.

However, the problem may still be continuing. The administrator of these instances said that `internal server error` occurred when logging into `https://instances.social/admin`. (I am not an administrator of these instances, it is not direct information, I'm sorry)

Perhaps contradiction occurred in the DB. For example: The administrator's record refers to the record of the deleted incorrect instance.

I am glad if you can check it.

**Comment by TheKinrar** [comment]
Which instance(s) please?

**Comment by mjyut** [comment]
> Which instance(s) please?

correct name: `mstdn.glorificatio.org`
incorrect name: `glorificatio@mstdn.glorificatio.org`

**Comment by mjyut** [comment]
@TheKinrar OK, thank you.
