### ISSUE TITLE
Admin space: Limit categories and languages

### ISSUE THREAD

**Issue by jeroenpraat** [TheKinrar/mastodon-instances#73]
Lately I notice some instances that misuse the languages and categories on instances.social and therefore joinmastodon.org. They select every language and every category, only to have as many users to sign up as possible (if it's a race :roll_eyes:). I had a new user who almost choose the wrong instance because of that and looking to the growing numbers of those instances a lot of other people did do. 

Isn't it an idea to limit the languages to 10 and categories to 5?  (maybe you or @gargron have a better amount?). Right now the instance picker on joinmastodon.org is unreliable, and that confuses and disappoints new users.

**Comment by Gargron** [comment]
I have long asked for this! I wanted only one or max. 2 categories to be selectable, and 1 primary language. General instances welcome all content but it makes no sense for them to appear under "art" and "music".

**Comment by jeroenpraat** [comment]
I think it's best to increase those numbers, especially languages. 

Let's take Todon.nl. This instance has several sub-communities speaking  Dutch, English, German and Spanish. And although activism is the primary category, there is also a sizeable LGBTQ community. 

So I would resuggest (as a reasonable compromise hopefully) 3 for categories and 5 for languages.

**Comment by TheKinrar** [comment]
Okay, I'm going to do this.
I think it will be two categories max.

As for the languages:
- 1 language => instances with not only one main language will probably go to a new "not language-specific instance" category
- n languages (two or three?) => keeps the current system

What are your thoughts on this?

**Comment by TheKinrar** [comment]
Okay, I've set the limit in the form.
I will probably consider all instances with more categories as general instance, to me this looks to be the best way to handle instances which currently have more than one category selected.

**Comment by jeroenpraat** [comment]
Thank you @TheKinrar. I try to understand the limits you have set. Did you set for both categories and languages a limit of 2? Or 2 and 1? 

Am I also right that this isn't live yet?

As for forcing the existing the existing instances: Maybe randomly picking 2 categories for them or empty the categories (both with an announcement instances should pick max. 2 categories).

**Comment by TheKinrar** [comment]
For now I only set the maximum for the categories, to 2.

> As for forcing the existing instances: Maybe randomly picking 2 categories for them or empty the categories (both with an announcement instances should pick max. 2 categories).

Well I think I'll do what I've said: consider instances with too many categories as general instances.

**Comment by jeroenpraat** [comment]
OK, thanks @TheKinrar . I'm looking forward to see it live. Closing this issue now.

**Comment by jeroenpraat** [comment]
Sorry, that wasn't clear to me.

**Comment by renatolond** [comment]
Adding my 2 cents for languages:
I would like to have a way to define "acceptable" languages, so to say. Masto.donte.com.br is a portuguese-speaking place, but we don't mind people using some other languages, as the team can moderate in those languages (others not so much as we would not be able to moderate them).

The 1-language could work for us, but it would be more clear if we could select secondary languages, even if it does not influence on search (ideally would just be more info, almost metadata)

**Comment by TheKinrar** [comment]
837203c62a5c70e738dff686777b348571127511 4a77daf1c7b46f569d86246f58211ff98ede9b66
instances with more than 2 categories selected (= instances that did not validate the form since 9ca1633ac9851e6c70a96883409b4988e2316bec) won't show when selecting a category on joinmastodon.org.
