### ISSUE TITLE
Updated instance data doesn't get fetched and is incomplete since over half a year

### ISSUE THREAD

**Issue by koyuawsmbrtn** [TheKinrar/mastodon-instances#77]
Title says it all. Instance is koyu.space.
Note on that: My password got reset recently so that might be why :thinking:

**Comment by wioxjk** [comment]
I have the same issue
social.linux.pizza

**Comment by downeym** [comment]
Same here: https://instances.social/floss.social
It seems that some instances are kept updated, but some are not ...

**Comment by downeym** [comment]
Of note, all three instances mentioned here have the following update timestamp:

`Last Observatory update: Tue Jul 10 2018`

**Comment by TheKinrar** [comment]
Okay, so these three instances were excluded from instance checks but I can't find why; this usually happens when an instance fakes some data or is not a real instance but it doesn't look like it was the case here. It should be fixed for these three instances. Keep this issue opened as I need to figure out what has been going on.

**Comment by downeymj** [comment]
https://instances.social/floss.social is no longer being checked but was getting errors up until the time it stopped. 
https://instances.social/social.linux.pizza seems to still be checking but getting errors.

Both of these instances are hosted on the same server by the same provider.

**Comment by TheKinrar** [comment]
Should be fixed for floss.social. @downeymj 
Errors on social.linux.pizza - and others - are fine as long as they're not happening too much; I agree "too much" should be defined, anyway it's fine in your instance logs :)

**Comment by downeymj** [comment]
Thank you!
