### ISSUE TITLE
getting invalid instance message after registering my instance

### ISSUE THREAD

**Issue by syndicato-de-gato** [TheKinrar/mastodon-instances#80]
Not able to login to instances.social to add the info about my instance. I registered and was never able to login after confirming my email. 

I get an error message that says "invalid instance" after I registered my instance on the instance.social site. I am using the correct email and password that i registered with.

Any suggestions?

**Comment by TheKinrar** [comment]
This is really too old, I'm closing this. Feel free to reopen it if needed, in which case please specify instance name
