### ISSUE TITLE
problem with unicode/punicode domains?

### ISSUE THREAD

**Issue by norayr** [TheKinrar/mastodon-instances#86]
hello,
I signed up, confirmed my mastodon account in order to add a language/my node to your database.

after the registration i cannot log in.

I suspect, that's because though the sign up page recognized unicode domain name, sign in code doesn't accept neither unicode, nor punicode domain names.

can you check? i believe you'll deduce who am i.

**Comment by TheKinrar** [comment]
Can you please tell me which instance you own? Sadly I could not deduce who you are

**Comment by TheKinrar** [comment]
Closing as this issue obviously lacks info (see previous message)
