### ISSUE TITLE
Missing column for some instances in JSON

### ISSUE THREAD

**Issue by Sp3r4z** [TheKinrar/mastodon-instances#9]
For some instances, column "openRegistrations" is missing.

Two examples, for: 
- mastodon.dupr.at
- social.mashek.net

I've checked this two servers don't respond well. But we have a JSON entry where this coloumn is missing.

**Comment by TheKinrar** [comment]
This is because those servers are down and have never been up since this column has been added.

Nothing I can do here, I just don't have the value.

**Comment by Sp3r4z** [comment]
I've thought about that too, I just mention it. 

Thanks for your answer.
