### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by mahaer-mahmud** [TheKinrar/mastodon-instances#94]
Whenever I try to access this website, I get a 502 gateway error (as seen on the screenshot below).

I've tried changing my DNS servers back to my ISP's (from those of Cloudflare) and using a proxy and VPN.

Thanks in advance. I am thinking of finding new instances.

![502 gateway error](https://user-images.githubusercontent.com/21954283/76144810-b32a8500-60a5-11ea-8384-6ab1542027e0.png)

**Comment by TheKinrar** [comment]
Fixed, thanks. One sever crashed and did not recover.
