### ISSUE TITLE
Using the last version of Brave on Android, no link and button works

### ISSUE THREAD

**Issue by Slonner** [TheKinrar/mastodon-instances#96]
From the application Tusky, it is proposed to make an tour about hosting in Mastodon and others "P2P social media" so if I found the idea interesting.

I click on a link which drive me on https://instances.social/.

On this site, 2 buttons = 2 links = the tour sold before + what I think is a hidden menu on top on right.

Only the link to Git Hub worked allowing me to report this problem.

I am no engineer at all but I could make a very good alpha/beta tester because if they're is a bug, it has to happen on me.

Even in the RL / Matrix .... 😅

Hope I could helped you ladys and guys.

Julien

**Comment by TheKinrar** [comment]
Works fine on latest version of Brave for Android.
